### PR TITLE
update link

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by askeblad** [comment]
@hvr

can you merge

**Comment by ghost** [comment]
@RyanGlScott can you merge

**Comment by RyanGlScott** [comment]
I don't have the necessary permissions for this repo, sorry.

**Comment by ghost** [comment]
@igfoo have you write authority

**Comment by igfoo** [comment]
Doesn't look like I do either, sorry.

**Comment by ghost** [comment]
@hvr five years ago made the sole PR merge to this repo

**Pull request closed without merging**
